"""Regenerate the auto-maintained status block in README.md and docs/STATUS.md
from the committed data. Run by CI on every push to main; safe to run locally.

Idempotent: the block only changes when the underlying data changes (dates come
from git history, not the clock), so CI's auto-commit never loops.
"""
import csv
import subprocess
import sys
from collections import Counter

from common import ACP_OBJECTS, DATA, DOCS, REPO, SNAPSHOT

START, END = '<!-- STATUS:START -->', '<!-- STATUS:END -->'


def git_date(*paths):
    try:
        out = subprocess.run(['git', 'log', '-1', '--format=%cs', '--', *paths],
                             cwd=REPO, capture_output=True, text=True, check=True).stdout.strip()
        return out or 'uncommitted'
    except Exception:
        return 'unknown'


def build():
    rows = list(csv.DictReader(open(DATA / 'XO_Reference_Matrix.csv', encoding='utf-8-sig')))
    disp = Counter(r['disposition'].split(' ')[0].split('(')[0] for r in rows)
    keep = sum(1 for r in rows if r['disposition'].startswith(('RELABEL', 'KEEP', 'REPURPOSE')))
    retire = sum(1 for r in rows if r['disposition'].startswith('RETIRE'))
    la_fields = [r for r in rows if r['category'] in ('keep20', 'la_field', 'la_gen2', 'la_identity', 'retire_resolved', 'la_adjacent')]
    la_keep = sum(1 for r in la_fields if r['disposition'].startswith('RELABEL'))
    searches = sum(1 for _ in csv.DictReader(open(DATA / 'XO_Search_Cleanup_List.csv', encoding='utf-8-sig')))
    acp = sorted(p.stem for p in ACP_OBJECTS.glob('*.xml') if not p.stem.startswith('custform_'))
    acp_new = sum(1 for a in acp if a.startswith('custitem_xo_'))
    acp_relabel = len(acp) - acp_new
    forms = sorted(p.stem for p in ACP_OBJECTS.glob('custform_*.xml'))

    lines = [
        START,
        f'_Auto-generated by `scripts/build_status.py` - do not edit by hand. Data last changed: **{git_date("data")}** - '
        f'ACP last changed: **{git_date("sdf")}** - corpus snapshot: **{SNAPSHOT}**._',
        '',
        '| Metric | Value |',
        '|---|---|',
        f'| Sweep targets in matrix | {len(rows)} |',
        f'| LA fields surviving (relabel) / retiring | **{la_keep}** / {len(la_fields) - la_keep} |',
        f'| Targets KEEP-family / RETIRE-family | {keep} / {retire} |',
        f'| Saved searches needing cleanup before inactivation | **{searches}** (`data/XO_Search_Cleanup_List.csv`) |',
        f'| SDF ACP field objects | **{len(acp)}** ({acp_relabel} relabels + {acp_new} new `custitem_xo_*`) |',
        f'| SDF-owned entry form | ' + (', '.join(f'`{f}`' for f in forms) if forms else 'none') + ' |',
        '',
        '**Disposition tally:** ' + ', '.join(f'{k} {v}' for k, v in sorted(disp.items())),
        END,
    ]
    return '\n'.join(lines)


def splice(path, block):
    text = path.read_text(encoding='utf-8')
    if START not in text or END not in text:
        raise SystemExit(f'{path} is missing the {START} / {END} markers')
    head, rest = text.split(START, 1)
    _old, tail = rest.split(END, 1)
    new = head + block + tail
    changed = new != text
    if changed:
        path.write_text(new, encoding='utf-8', newline='\n')
    return changed


def main():
    check = '--check' in sys.argv
    block = build()
    changed = [str(p.relative_to(REPO)) for p in (REPO / 'README.md', DOCS / 'STATUS.md') if splice(p, block)]
    if changed:
        print('status block updated in:', ', '.join(changed))
        if check:
            sys.exit(1)
    else:
        print('status block up to date')


if __name__ == '__main__':
    main()
