"""Generate the SDF ACP field objects under sdf/xo-cutover-acp/src/Objects.

Three kinds of field objects:
  * RELABELS       - copied from the corpus, <label>/<help> patched, placement applied
  * PLACEMENT_ONLY - copied from the corpus unchanged except placement (labels already right)
  * NEW_FIELDS     - authored from TEMPLATE

Placement = the field's default <subtab>, per docs/Item_Form_Redesign.md. Valid standard
values for itemcustomfield (SDF generic_item_tab): ITEMMAIN, ITEMINVENTORY,
ITEMPURCHASINGINVENTORY, ITEMBASIC, ITEMCOMMUNICATION, ITEMLOCATIONS, ITEMVENDORS,
ITEMSYSTEMINFORMATION, ITEMMATRIX. There is NO Sales/Pricing or Accounting default
(NetSuite: "subtab must not be ITEMPRICING", SB1 2026-08-28), so those fields default
blank and the form places them via Move Elements.

Subtab objects live in src/Objects/subtab/ and are hand-managed (imported + relabeled).
The entry form custform_xo_inventory_item.xml is generated by scripts/build_form.py and is
left alone here (SDF *can* deploy it - see findings 4a; the 2026-08-25 conclusion was wrong).
"""
import re

from common import ACP_OBJECTS, CORPUS

FIELD_CORPUS = CORPUS / 'objects' / 'itemcustomfield'

SPECS = '[scriptid=custtab_25_t2379072_560]'      # relabeled "Specifications"
INTEG = '[scriptid=custtab_xo_integrations]'      # new "Integrations"
MAIN = 'ITEMMAIN'
PURCH = 'ITEMINVENTORY'
FORM_PLACED = ''   # no SDF default exists for Sales/Pricing; blank = Custom until the form moves it

# scriptid -> (new label, help text)
RELABELS = {
    'custitem_la_image': ('Primary Image', 'Primary product image. XO source: Image Path. Gallery images 1-15 live in XO.'),
    'custitem_la_product_url': ('Item URL', 'XO item URL for internal staff lookup. XO source: Item URL (relative path - pipeline prepends XO domain).'),
    'custitem_la_safety_listing': ('Safety Rating', 'Safety certification (ETL/UL). NOTE: field content was always the safety listing despite the old label. XO source: Extra-Safety Rating.'),
    'custitem_la_safety_rating': ('Location Rating', 'Location rating (Damp/Wet/Dry). NOTE: field content was always the location rating despite the old label. XO source: Extra-Location Rating.'),
    'custitem_la_bulb_type': ('Bulb Type', 'XO source: Extra-Bulb Type (XO prefixes light source, e.g. "LED B10.5").'),
    'custitem_la_upc': ('UPC / GTIN', 'XO ships GTIN-14 with leading zeros. Store as-is; strip leading zeros only for comparison.'),
    'custitem_la_color_temperature': ('Kelvin', 'XO source: Extra-Kelvin.'),
    'custitem_la_light_output': ('Lumens', 'XO source: Extra-Initial Lumens.'),
    'custitem7': ('XO Item ID', 'XO permanent numeric item identity. Source: ItemID column (NOT XOItemID, which is Excel-mangled in the export).'),
    'custitem_la_max_wattage': ('Wattage', 'Exact wattage. XO source: Extra-Bulb Wattage with units stripped ("60 W" -> 60). Kept per 2026-08-25 decision (543,145 rows) - 21st surviving LA field.'),
}

# scriptid -> (label, fieldtype, help)
NEW_FIELDS = [
    ('custitem_xo_umap', 'XO UMAP', 'CURRENCY', 'XO UMAP pricing tier. (Labeled XO UMAP to avoid collision with legacy custitem_la_umap label.)'),
    ('custitem_xo_backorder_date', 'Back Order Date', 'DATE', 'Manufacturer back-order date from XO. Informational; inventory does not sync.'),
    ('custitem_xo_in_stock', 'XO In Stock', 'INTEGER', 'Manufacturer stock from XO. Informational only; inventory intentionally does not sync.'),
    ('custitem_xo_order_multiple', 'Order Multiple', 'INTEGER', 'XO purchasing constraint.'),
    ('custitem_xo_order_minimum', 'Order Minimum', 'INTEGER', 'XO purchasing constraint.'),
    ('custitem_xo_last_changed', 'XO Last Changed', 'DATE', 'XO change-date quartet: any change.'),
    ('custitem_xo_availability_changed', 'XO Availability Changed', 'DATE', 'XO change-date quartet: availability.'),
    ('custitem_xo_catalog_changed', 'XO Catalog Changed', 'DATE', 'XO change-date quartet: catalog data.'),
    ('custitem_xo_price_changed', 'XO Price Changed', 'DATE', 'XO change-date quartet: pricing.'),
    ('custitem_xo_vendor_disc_cost', 'Vendor Discounted Cost', 'CURRENCY', 'XO cost family. Item Cost itself lands in native cost.'),
    ('custitem_xo_cost_w_shipping', 'Cost With Shipping', 'CURRENCY', 'XO cost family.'),
    ('custitem_xo_kelvin_bucket', 'Kelvin Bucket', 'TEXT', 'Normalized facet bucket. XO source: Standard-Kelvin.'),
    ('custitem_xo_lumens_bucket', 'Lumens Bucket', 'TEXT', 'Normalized facet bucket. XO source: Standard-Lumens.'),
    ('custitem_xo_wattage_bucket', 'Wattage Bucket', 'TEXT', 'Normalized facet bucket. XO source: Standard-Wattage ("60w" -> strip units).'),
    ('custitem_xo_voltage_bucket', 'Voltage Bucket', 'TEXT', 'Normalized facet bucket. XO source: Standard-Voltage.'),
    ('custitem_xo_keywords', 'XO Keywords', 'TEXTAREA', 'Search keywords from XO.'),
    ('custitem_xo_prop65', 'Prop 65', 'TEXT', 'CA Prop 65 flag, stored raw from XO (no transform risk).'),
    ('custitem_xo_prop65_desc', 'Prop 65 Description', 'TEXTAREA', 'CA Prop 65 warning text from XO.'),
    ('custitem_xo_title20', 'Title 20', 'TEXT', 'CA Title 20 compliance, stored raw from XO.'),
    ('custitem_xo_title24', 'Title 24', 'TEXT', 'CA Title 24 compliance, stored raw from XO.'),
]

# Default subtab for every Premier-owned custom field that survives (docs/Item_Form_Redesign.md)
PLACEMENT = {
    'custitem_la_product_name': MAIN, 'custitem_la_upc': MAIN, 'custitem_la_collection': MAIN,
    'custitem_la_finish': MAIN, 'custitem_la_image': MAIN, 'custitem_la_product_url': MAIN, 'custitem6': MAIN,
    'custitem_xo_in_stock': PURCH, 'custitem_xo_backorder_date': PURCH, 'custitem_xo_order_minimum': PURCH,
    'custitem_xo_order_multiple': PURCH, 'custitem_xo_vendor_disc_cost': PURCH, 'custitem_xo_cost_w_shipping': PURCH,
    'custitem_zastro_special_order': PURCH,
    'custitem5': FORM_PLACED, 'custitem_xo_umap': FORM_PLACED,
    'custitem_la_width': SPECS, 'custitem_la_height': SPECS, 'custitem_la_length': SPECS,
    'custitem_la_bulb_type': SPECS, 'custitem_la_bulb_base': SPECS, 'custitem_la_number_of_bulbs': SPECS,
    'custitem_la_max_wattage': SPECS, 'custitem_la_color_temperature': SPECS, 'custitem_la_light_output': SPECS,
    'custitem_la_cri': SPECS, 'custitem_la_voltage': SPECS, 'custitem_la_dimmable': SPECS,
    'custitem_la_material': SPECS, 'custitem_la_safety_listing': SPECS, 'custitem_la_safety_rating': SPECS,
    'custitem_xo_prop65': SPECS, 'custitem_xo_prop65_desc': SPECS, 'custitem_xo_title20': SPECS,
    'custitem_xo_title24': SPECS, 'custitem_spec_sheet_link': SPECS,
    'custitem_xo_kelvin_bucket': SPECS, 'custitem_xo_lumens_bucket': SPECS,
    'custitem_xo_wattage_bucket': SPECS, 'custitem_xo_voltage_bucket': SPECS,
    'custitem7': INTEG, 'custitem_xo_last_changed': INTEG, 'custitem_xo_availability_changed': INTEG,
    'custitem_xo_catalog_changed': INTEG, 'custitem_xo_price_changed': INTEG, 'custitem_xo_keywords': INTEG,
    'custitem_shopify_store': INTEG, 'custitem_sync_shopify': INTEG, 'custitem_isonline': INTEG,
    'custitem_list_on_shopify_temporary_fie': INTEG, 'custitem_leaves_shopify_inventory': INTEG,
}
PLACEMENT_ONLY = [sid for sid in PLACEMENT if sid not in RELABELS and not sid.startswith('custitem_xo_')]

TEMPLATE = '''<itemcustomfield scriptid="{scriptid}">
  <accesslevel>2</accesslevel>
  <appliestogroup>F</appliestogroup>
  <appliestoinventory>T</appliestoinventory>
  <appliestokit>F</appliestokit>
  <appliestononinventory>F</appliestononinventory>
  <appliestoothercharge>F</appliestoothercharge>
  <appliestopricelist>F</appliestopricelist>
  <appliestoservice>F</appliestoservice>
  <appliestospecificitems>F</appliestospecificitems>
  <appliestosubplan>F</appliestosubplan>
  <applyformatting>F</applyformatting>
  <checkspelling>F</checkspelling>
  <defaultchecked>F</defaultchecked>
  <displaytype>NORMAL</displaytype>
  <encryptatrest>F</encryptatrest>
  <fieldtype>{fieldtype}</fieldtype>
  <globalsearch>F</globalsearch>
  <help>{help}</help>
  <includechilditems>F</includechilditems>
  <isformula>F</isformula>
  <ismandatory>F</ismandatory>
  <isparent>F</isparent>
  <itemsubtype>BOTH</itemsubtype>
  <label>{label}</label>
  <searchlevel>2</searchlevel>
  <showhierarchy>F</showhierarchy>
  <showinlist>F</showinlist>
  <storevalue>T</storevalue>
  <subtab>{subtab}</subtab>
</itemcustomfield>
'''

# elements the SDF validator rejects at Premier (features not enabled / newer UI-only fields)
STRIP = ['ismatrixoption', 'aidescription', 'enabletextenhance', 'itemmatrix',
         'ismhitemattribute', 'appliestovendor', 'appliestopartner']
SUBTAB_RE = re.compile(r'<subtab>.*?</subtab>', re.DOTALL)
NL = '\n'


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def strip_traps(xml):
    for el in STRIP:
        xml = re.sub(r'\s*<' + el + r'>.*?</' + el + '>', '', xml, flags=re.DOTALL)
    return xml


def set_subtab(xml, sid):
    """Force <subtab> to the planned home; add the element if the export lacks it."""
    if sid not in PLACEMENT:
        return xml
    tag = '<subtab>' + PLACEMENT[sid] + '</subtab>'
    if SUBTAB_RE.search(xml):
        return SUBTAB_RE.sub(tag, xml, count=1)
    return xml.replace('</itemcustomfield>', '  ' + tag + NL + '</itemcustomfield>')


def write(sid, xml, expected):
    (ACP_OBJECTS / (sid + '.xml')).write_text(xml, encoding='utf-8', newline=NL)
    expected.add(sid + '.xml')


def main():
    ACP_OBJECTS.mkdir(parents=True, exist_ok=True)
    expected = set()

    for sid, (label, help_text) in RELABELS.items():
        xml = (FIELD_CORPUS / (sid + '.xml')).read_text(encoding='utf-8')
        xml = re.sub(r'<label>.*?</label>', '<label>' + esc(label) + '</label>', xml, count=1, flags=re.DOTALL)
        xml = re.sub(r'<help>.*?</help>', '<help>' + esc(help_text) + '</help>', xml, count=1, flags=re.DOTALL)
        xml = set_subtab(strip_traps(xml), sid)
        write(sid, xml, expected)
        print('relabel:', sid, '->', label, '@', PLACEMENT.get(sid) or '(form-placed)')

    for sid in PLACEMENT_ONLY:
        xml = (FIELD_CORPUS / (sid + '.xml')).read_text(encoding='utf-8')
        xml = set_subtab(strip_traps(xml), sid)
        write(sid, xml, expected)
        print('place:  ', sid, '@', PLACEMENT[sid] or '(form-placed)')

    for sid, label, ftype, help_text in NEW_FIELDS:
        xml = TEMPLATE.format(scriptid=sid, label=esc(label), fieldtype=ftype, help=esc(help_text),
                              subtab=PLACEMENT.get(sid, SPECS))
        write(sid, xml, expected)
        print('new:    ', sid, '(' + ftype + ') @', PLACEMENT.get(sid, SPECS) or '(form-placed)')

    # remove stale top-level field objects (src/Objects/subtab/ is hand-managed and
    # untouched; the entry form belongs to scripts/build_form.py)
    expected.add('custform_xo_inventory_item.xml')
    for p in ACP_OBJECTS.glob('*.xml'):
        if p.name not in expected:
            p.unlink()
            print('removed stale object:', p.name)
    print('ACP field objects:', len([p for p in ACP_OBJECTS.glob('*.xml')
                                     if not p.name.startswith('custform_')]),
          '| subtab objects:', len(list((ACP_OBJECTS / 'subtab').glob('*.xml'))))


if __name__ == '__main__':
    main()
