/**
 * inboundEmailPO_sl.js
 *
 * Emails the vendor Purchase Order document for an inbound shipment.
 *
 * CHANGED FROM THE DEPLOYED VERSION: the header data, line data and rendering
 * now come from illuminet_po_data_lib -- the same module the print Suitelet
 * uses -- so the emailed PDF and the printed PDF are the same document. The
 * old getInboundData / getPOData / getPOSum are gone; they were the source of
 * the drift ("- None -", blank Date Created, blank Subtotal/Total).
 *
 * UNCHANGED: sendEmail, findVendor, the stamping (full record load/save, same
 * two fields, same order) and the window.close response are exactly as
 * deployed.
 *
 * ONE ADDITION, marked below: the preflight gate. The shared builder produces
 * preflight findings either way; without the gate the email path would send a
 * PO the print path refuses to print, and `force` is what populates the PL#
 * disambiguator on colliding lines. Delete the marked block if you want the
 * email path to send unconditionally.
 *
 *@NApiVersion 2.1
 *@NModuleScope Public
 *@NScriptType Suitelet
 */
define(['N/log', 'N/record', 'N/search', 'N/render', 'N/email', 'N/url', 'N/runtime',
        './illuminet_po_data_lib'],
function (log, record, search, render, email, url, runtime, poLib) {

  function onRequest(context) {
    const params = context.request.parameters;
    const originatingID = params.custom_id;
    const force = params.force === 'T';
    log.debug('originatingID', originatingID);

    // Data + preflight + totals, all from the shared document layer.
    const doc = poLib.buildDocument(originatingID, force);

    if (doc.lines.length === 0) return;

    // --- ADDED: preflight gate (delete this block to restore old behaviour) ---
    if (doc.preflight.errors.length > 0 && !force) {
      const self = url.resolveScript({
        scriptId: runtime.getCurrentScript().id,
        deploymentId: runtime.getCurrentScript().deploymentId,
        returnExternalUrl: false
      });
      context.response.write(poLib.buildPreflightHtml(
        doc.preflight,
        originatingID,
        self + '&custom_id=' + originatingID + '&force=T',
        'emailed to the vendor'
      ));
      return;
    }
    // --- end added block ---

    const pdfFile = poLib.generatePdf(doc.lines, doc.inboundData, poLib.TEMPLATE_ID);
    sendEmail(pdfFile, originatingID, doc.inboundData.doc);

    // Load the record only to set the timestamp and sent flag before saving.
    var shipmentRecord = record.load({ type: 'inboundshipment', id: originatingID });
    shipmentRecord.setValue({ fieldId: 'custrecord_zas_po_email_stamp', value: new Date() });
    shipmentRecord.setValue({ fieldId: 'custrecord_inbound_email_sent', value: true });
    shipmentRecord.save();

    context.response.write("<script>window.close();</script>");
  }

  const sendEmail = (pdfFile, originitatingID, doc) => {
    pdfFile.name = 'premierlighting_po' + doc + '.pdf'
    var returnVendor = findVendor(originitatingID)
    var mergeResult = render.mergeEmail({
      templateId: 4,
      entity: null,
      recipient: null,
      supportCaseId: null,
      transactionId: null,
      customRecord: null
    });
    var emailArr = new Array()
    log.debug('returnVendor', returnVendor)
    var senderId = 15383;

    var emailBody = mergeResult.body; // Use the body generated by the template

    var recipientEmail = returnVendor.email
    emailArr.push(recipientEmail)

    email.send({
      author: senderId,
      recipients: emailArr,
      subject: `PO ${doc} : new PO from Premier Lighting`,
      body: emailBody,
      attachments: [pdfFile],
      relatedRecords: {
        entityId: Number(returnVendor.id),
      },
    });
  }

  /**
   * Searches and returns vendor information associated with the inbound shipment.
   * @param {number} originatingID - The ID of the inbound shipment
   * @returns {Object} returnObj - Contains vendor ID and email
   */
  const findVendor = (originatingID) => {
    let returnObj = {};

    var inboundShipmentSearch = search.create({
      type: "inboundshipment",
      filters: [["internalid", "anyof", originatingID]],
      columns: [
        search.createColumn({ name: "email", join: "vendor" }),
        search.createColumn({ name: "internalid", join: "vendor" })
      ]
    });

    inboundShipmentSearch.run().each(function (result) {
      returnObj.id = result.getValue({ name: 'internalid', join: 'vendor' });
      returnObj.email = result.getValue({ name: 'email', join: 'vendor' });
      return true;
    });

    return returnObj;
  };

  return { onRequest: onRequest };
});